name: Build and Push Docker Images

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push web image
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          tags: ghcr.io/safaesiraji00/assignment3/web:latest

      - name: Skip DB image (Postgres is official)
        run: echo "PostgreSQL image not custom — using official image"
